# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineracao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arquivo',
        ),
    ]
